services:
  app:
    build:
      context: ./docker/7.4/
      dockerfile: Dockerfile
    image: 'easycodebr/php-fpm:7.4'
    container_name: omeurestaurante-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
    networks:
      - app-network
    depends_on:
      - db
  webserver:
    image: 'nginx:alpine'
    container_name: omeurestaurante-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - '5173:5173'
    volumes:
      - './:/var/www/html'
      - './docker/7.4/nginx/app.conf:/etc/nginx/conf.d/app.conf'
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: 'mysql/mysql-server:8.0'
    container_name: omeurestaurante-db
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'easycodebr-dbdata:/var/lib/mysql'
      - './docker/dump/:/docker-entrypoint-initdb.d/'
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  easycodebr-dbdata:
    driver: local
